project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  elsevier-pdf:
    keep-tex: true 
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
      layout: onecolumn
      cite-style: authoryear
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

execute:
  freeze: false



